<?php

namespace Database\Seeders;

use App\Models\ModerationRule;
use Illuminate\Database\Seeder;

class ModerationRuleSeeder extends Seeder
{
    public function run(): void
    {
        $rules = [
            [
                'rule_key' => 'bad_word_warn_idiot',
                'rule_type' => 'bad_word',
                'pattern' => 'idiot',
                'threshold' => null,
                'action' => 'warn',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'low',
            ],
            [
                'rule_key' => 'bad_word_warn_stupid',
                'rule_type' => 'bad_word',
                'pattern' => 'stupid',
                'threshold' => null,
                'action' => 'warn',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'low',
            ],
            [
                'rule_key' => 'bad_word_review_shut_up',
                'rule_type' => 'bad_word',
                'pattern' => 'shut up',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'medium',
            ],
            [
                'rule_key' => 'bad_word_review_nude',
                'rule_type' => 'bad_word',
                'pattern' => 'send nudes',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'high',
            ],
            [
                'rule_key' => 'bad_word_review_sex',
                'rule_type' => 'bad_word',
                'pattern' => 'sex chat',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'high',
            ],
            [
                'rule_key' => 'spam_repeat_kick_3_in_1m',
                'rule_type' => 'spam',
                'pattern' => null,
                'threshold' => 3,
                'action' => 'kick',
                'duration_minutes' => 1,
                'is_active' => true,
                'severity' => 'high',
            ],
            [
                'rule_key' => 'flooding_warn_6_in_1m',
                'rule_type' => 'flooding',
                'pattern' => null,
                'threshold' => 6,
                'action' => 'warn',
                'duration_minutes' => 1,
                'is_active' => true,
                'severity' => 'medium',
            ],
            [
                'rule_key' => 'link_review_generic',
                'rule_type' => 'link',
                'pattern' => null,
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'high',
            ],
            [
                'rule_key' => 'custom_review_send_me_otp',
                'rule_type' => 'custom',
                'pattern' => 'send me otp',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'critical',
            ],
            [
                'rule_key' => 'custom_review_whatsapp',
                'rule_type' => 'custom',
                'pattern' => 'whatsapp me',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'medium',
            ],
            [
                'rule_key' => 'custom_review_telegram',
                'rule_type' => 'custom',
                'pattern' => 'telegram me',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'medium',
            ],
            [
                'rule_key' => 'custom_review_send_money',
                'rule_type' => 'custom',
                'pattern' => 'send money first',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'high',
            ],
            [
                'rule_key' => 'custom_review_go_die',
                'rule_type' => 'custom',
                'pattern' => 'go die',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'high',
            ],
            [
                'rule_key' => 'custom_review_kill_yourself',
                'rule_type' => 'custom',
                'pattern' => 'kill yourself',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'critical',
            ],
            [
                'rule_key' => 'custom_review_crypto_investment',
                'rule_type' => 'custom',
                'pattern' => 'crypto investment',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'high',
            ],
            [
                'rule_key' => 'custom_review_cashapp',
                'rule_type' => 'custom',
                'pattern' => 'cashapp',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'high',
            ],
            [
                'rule_key' => 'custom_review_upi_id',
                'rule_type' => 'custom',
                'pattern' => 'upi id',
                'threshold' => null,
                'action' => 'review',
                'duration_minutes' => null,
                'is_active' => true,
                'severity' => 'high',
            ],
            [
                'rule_key' => 'custom_block_template_critical_phrase',
                'rule_type' => 'custom',
                'pattern' => 'blocked phrase',
                'threshold' => null,
                'action' => 'block',
                'duration_minutes' => null,
                'is_active' => false,
                'severity' => 'critical',
            ],
            [
                'rule_key' => 'flooding_block_template_12_in_1m',
                'rule_type' => 'flooding',
                'pattern' => null,
                'threshold' => 12,
                'action' => 'block',
                'duration_minutes' => 1,
                'is_active' => false,
                'severity' => 'critical',
            ],
        ];

        foreach ($rules as $rule) {
            ModerationRule::query()->updateOrCreate(
                ['rule_key' => $rule['rule_key']],
                $rule,
            );
        }
    }
}
